#include "CryptPHP.h"
#include "FileUtil.h"
#include "ResourceManager.h"

#include <array>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <thread>
using namespace std;
namespace fs = std::filesystem;

#define BRAND_PRODUCT_NAME "CryptPHP"
#define BRAND_VERSION "v1.0.0"
#define BRAND_REPO_URL "https://github.com/mohit-hasan/crypt-php"

CryptPHP::CryptPHP() : currentPhase(Phase::Ready) {}
CryptPHP::~CryptPHP() {}

void CryptPHP::setLogCallback(function<void(const string &)> cb) {
  logCallback = cb;
}

void CryptPHP::log(const string &msg) {
  if (logCallback)
    logCallback(msg);
}

CryptPHP::Phase CryptPHP::getCurrentPhase() const { return currentPhase; }

bool CryptPHP::runCommandWithOutput(const string &command) {
  array<char, 256> buffer;
#ifdef _WIN32
#define POPEN _popen
#define PCLOSE _pclose
#else
#define POPEN popen
#define PCLOSE pclose
#endif
  FILE *pipe = POPEN((command + " 2>&1").c_str(), "r");
  if (!pipe) {
    log("  [ERR] popen() failed!");
    return false;
  }
  while (fgets(buffer.data(), buffer.size(), pipe) != nullptr) {
    string line(buffer.data());
    // cleaner log output
    if (!line.empty() && line.back() == '\n')
      line.pop_back();
    log("  " + line);
  }
  int returnCode = PCLOSE(pipe);
  return returnCode == 0;
}

// helper: convert comma separated string to php array literal or null
static string toPhpArray(const string &csv) {
  if (csv.empty())
    return "null";
  stringstream out;
  out << "array(";
  stringstream ss(csv);
  string token;
  bool first = true;
  while (getline(ss, token, ',')) {
    // trim whitespaces
    size_t start = token.find_first_not_of(" \t");
    size_t end = token.find_last_not_of(" \t");
    if (start == string::npos)
      continue;
    token = token.substr(start, end - start + 1);
    if (!first)
      out << ", ";
    out << "'" << token << "'";
    first = false;
  }
  out << ")";
  return out.str();
}

static string SerializeYakPro(const CryptPHP::YakProSettings &s) {
  stringstream ss;
  // =====================================================================
  // critical: line 1 must be exactly "<?php"
  //           line 2 must be exactly "// YAK Pro - Php Obfuscator: Config File"
  // this is validated by check_config_file() in yakpro-po/include/functions.php
  // =====================================================================
  ss << "<?php\n";
  ss << "// YAK Pro - Php Obfuscator: Config File\n";
  ss << "//"
        "======================================================================"
        "==\n";
  ss << "// Generated by CryptPHP - https://github.com/mohit-hasan/crypt-php\n";
  ss << "//"
        "======================================================================"
        "==\n";
  ss << "\n";

  // pre defined classes
  ss << "$conf->t_ignore_pre_defined_classes = '"
     << s.t_ignore_pre_defined_classes << "';\n";
  ss << "\n";

  // ignore exact names
  ss << "$conf->t_ignore_constants            = "
     << toPhpArray(s.t_ignore_constants) << ";\n";
  ss << "$conf->t_ignore_variables            = "
     << toPhpArray(s.t_ignore_variables) << ";\n";
  ss << "$conf->t_ignore_functions            = "
     << toPhpArray(s.t_ignore_functions) << ";\n";
  ss << "$conf->t_ignore_class_constants      = "
     << toPhpArray(s.t_ignore_class_constants) << ";\n";
  ss << "$conf->t_ignore_methods              = "
     << toPhpArray(s.t_ignore_methods) << ";\n";
  ss << "$conf->t_ignore_properties           = "
     << toPhpArray(s.t_ignore_properties) << ";\n";
  ss << "$conf->t_ignore_classes              = "
     << toPhpArray(s.t_ignore_classes) << ";\n";
  ss << "$conf->t_ignore_interfaces           = "
     << toPhpArray(s.t_ignore_interfaces) << ";\n";
  ss << "$conf->t_ignore_traits               = "
     << toPhpArray(s.t_ignore_traits) << ";\n";
  ss << "$conf->t_ignore_namespaces           = "
     << toPhpArray(s.t_ignore_namespaces) << ";\n";
  ss << "$conf->t_ignore_labels               = "
     << toPhpArray(s.t_ignore_labels) << ";\n";
  ss << "\n";

  // ignore prefix names
  ss << "$conf->t_ignore_constants_prefix       = "
     << toPhpArray(s.t_ignore_constants_prefix) << ";\n";
  ss << "$conf->t_ignore_variables_prefix       = "
     << toPhpArray(s.t_ignore_variables_prefix) << ";\n";
  ss << "$conf->t_ignore_functions_prefix       = "
     << toPhpArray(s.t_ignore_functions_prefix) << ";\n";
  ss << "$conf->t_ignore_class_constants_prefix = "
     << toPhpArray(s.t_ignore_class_constants_prefix) << ";\n";
  ss << "$conf->t_ignore_properties_prefix      = "
     << toPhpArray(s.t_ignore_properties_prefix) << ";\n";
  ss << "$conf->t_ignore_methods_prefix         = "
     << toPhpArray(s.t_ignore_methods_prefix) << ";\n";
  ss << "$conf->t_ignore_classes_prefix         = "
     << toPhpArray(s.t_ignore_classes_prefix) << ";\n";
  ss << "$conf->t_ignore_interfaces_prefix      = "
     << toPhpArray(s.t_ignore_interfaces_prefix) << ";\n";
  ss << "$conf->t_ignore_traits_prefix          = "
     << toPhpArray(s.t_ignore_traits_prefix) << ";\n";
  ss << "$conf->t_ignore_namespaces_prefix      = "
     << toPhpArray(s.t_ignore_namespaces_prefix) << ";\n";
  ss << "$conf->t_ignore_labels_prefix          = "
     << toPhpArray(s.t_ignore_labels_prefix) << ";\n";
  ss << "\n";

  // parser and scramble
  ss << "$conf->parser_mode     = '" << s.parser_mode << "';\n";
  ss << "$conf->scramble_mode   = '" << s.scramble_mode << "';\n";
  ss << "$conf->scramble_length = " << s.scramble_length << ";\n";
  ss << "\n";

  // php extensions to obfuscate
  ss << "$conf->t_obfuscate_php_extension = array('"
     << s.t_obfuscate_php_extension << "');\n";
  ss << "\n";

  // obfuscation toggles
  ss << "$conf->obfuscate_constant_name       = "
     << (s.obfuscate_constant_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_variable_name       = "
     << (s.obfuscate_variable_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_function_name       = "
     << (s.obfuscate_function_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_class_name          = "
     << (s.obfuscate_class_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_interface_name      = "
     << (s.obfuscate_interface_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_trait_name          = "
     << (s.obfuscate_trait_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_class_constant_name = "
     << (s.obfuscate_class_constant_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_property_name       = "
     << (s.obfuscate_property_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_method_name         = "
     << (s.obfuscate_method_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_namespace_name      = "
     << (s.obfuscate_namespace_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_label_name          = "
     << (s.obfuscate_label_name ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_if_statement        = "
     << (s.obfuscate_if_statement ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_loop_statement      = "
     << (s.obfuscate_loop_statement ? "true" : "false") << ";\n";
  ss << "$conf->obfuscate_string_literal      = "
     << (s.obfuscate_string_literal ? "true" : "false") << ";\n";
  ss << "\n";

  // shuffling
  ss << "$conf->shuffle_stmts                = "
     << (s.shuffle_stmts ? "true" : "false") << ";\n";
  ss << "$conf->shuffle_stmts_min_chunk_size = "
     << s.shuffle_stmts_min_chunk_size << ";\n";
  ss << "$conf->shuffle_stmts_chunk_mode     = '" << s.shuffle_stmts_chunk_mode
     << "';\n";
  ss << "$conf->shuffle_stmts_chunk_ratio    = " << s.shuffle_stmts_chunk_ratio
     << ";\n";
  ss << "\n";

  // general
  ss << "$conf->strip_indentation               = "
     << (s.strip_indentation ? "true" : "false") << ";\n";
  ss << "$conf->abort_on_error                  = "
     << (s.abort_on_error ? "true" : "false") << ";\n";
  ss << "$conf->confirm                         = true;\n";
  ss << "$conf->silent                          = "
     << (s.silent ? "true" : "false") << ";\n";
  ss << "$conf->allow_and_overwrite_empty_files = "
     << (s.allow_and_overwrite_empty_files ? "true" : "false") << ";\n";
  ss << "$conf->follow_symlinks                 = "
     << (s.follow_symlinks ? "true" : "false") << ";\n";
  ss << "$conf->max_nested_directory            = " << s.max_nested_directory
     << ";\n";
  ss << "\n";

  // optional user comment
  if (!s.user_comment.empty()) {
    ss << "$conf->user_comment = '" << s.user_comment << "';\n";
  } else {
    ss << "$conf->user_comment = null;\n";
  }

  // optional extract comment range
  if (s.extract_comment_from_line > 0 && s.extract_comment_to_line > 0) {
    ss << "$conf->extract_comment_from_line = " << s.extract_comment_from_line
       << ";\n";
    ss << "$conf->extract_comment_to_line   = " << s.extract_comment_to_line
       << ";\n";
  } else {
    ss << "$conf->extract_comment_from_line = null;\n";
    ss << "$conf->extract_comment_to_line   = null;\n";
  }

  ss << "\n?>\n";
  return ss.str();
}

void CryptPHP::start(const Config &config) {
  thread([this, config]() {
    try {
      filesystem::path tempBase =
          filesystem::temp_directory_path() / "php_cryptphp_build";
      filesystem::path rawDir = tempBase / "raw";
      filesystem::path encDir = tempBase / "enc";

      log("=== Phase 0: Initializing build environment ===");
      if (filesystem::exists(tempBase))
        filesystem::remove_all(tempBase);
      filesystem::create_directories(rawDir);
      filesystem::create_directories(encDir);

      // sync/mirror project
      currentPhase = Phase::Syncing;
      log("=== Phase 0: Mirroring project ===");
      if (!FileUtil::MirrorDirectory(config.projectPath, rawDir,
                                     config.ignorePatterns, logCallback)) {
        throw runtime_error("Project Sync (Mirroring) failed.");
      }

      // restore framework directory shells that may have been excluded for
      // laravel projects
      fs::path srcRoot = fs::path(config.projectPath);
      if (fs::exists(srcRoot / "storage")) {
        fs::create_directories(rawDir / "storage/framework/cache");
        fs::create_directories(rawDir / "storage/framework/sessions");
        fs::create_directories(rawDir / "storage/framework/views");
        fs::create_directories(rawDir / "storage/app/public");
        fs::create_directories(rawDir / "storage/logs");
      }
      if (fs::exists(srcRoot / "bootstrap")) {
        fs::create_directories(rawDir / "bootstrap/cache");
      }

      // generate yakpro-po.cnf into the mirrored project root
      // this is where YakPro will look per its config search order:
      //    1. --config-file arg (absolute path)
      //    2. current_working_directory/yakpro-po.cnf
      filesystem::path cnfPath = rawDir / "yakpro-po.cnf";
      {
        ofstream cnfOfs(cnfPath);
        if (!cnfOfs.is_open())
          throw runtime_error("Cannot write yakpro-po.cnf to: " +
                              cnfPath.string());
        cnfOfs << SerializeYakPro(config.yakPro);
        cnfOfs.close();
      }
      log("  [OK] Config written: " + cnfPath.string());

      // phase 1: YakPro obfuscation
      currentPhase = Phase::YAKProRunning;
      log("=== Phase 1: Running YakPro granular obfuscation ===");
      log("=== Extracting embedded YAK Pro... ===");
      string yakTempPath = (tempBase / "yakpro").string();
      string yakMain = ResourceManager::ExtractAll(yakTempPath);
      if (yakMain.empty())
        throw runtime_error(
            "YAK Pro extraction failed. Run setup_resources.sh first.");

      for (const auto &p : config.obfuscateFolders) {
        filesystem::path src = rawDir / p;
        filesystem::path dst = encDir / p;
        if (!filesystem::exists(src))
          continue;

        if (filesystem::is_directory(src)) {
          // directory mode: YakPro creates yakpro-po/obfuscated/ inside dst
          string cmd = "php \"" + yakMain + "\"" + " \"" + src.string() + "\"" +
                       " -o \"" + dst.string() + "\"" + " --config-file \"" +
                       cnfPath.string() + "\"" + " -y > /dev/null 2>&1";
          runCommandWithOutput(cmd);
        } else {
          // file mode: ensure parent dir in encDir exists
          filesystem::create_directories(dst.parent_path());
          string cmd = "php \"" + yakMain + "\"" + " \"" + src.string() + "\"" +
                       " -o \"" + dst.string() + "\"" + " --config-file \"" +
                       cnfPath.string() + "\"" + " -y > /dev/null 2>&1";
          runCommandWithOutput(cmd);
        }
      }

      //phase 1b: strip YakPro banner & inject custom branding
      currentPhase = Phase::StrippingBanners;
      log("=== Phase 1b: Stripping YakPro banners & branding ===");

      string
      brandBanner  = "/*========================================\n";
      brandBanner += " * " + string(BRAND_PRODUCT_NAME) + "  |  " + BRAND_VERSION + "\n";
      brandBanner += " * Repository: " + string(BRAND_REPO_URL) + "\n";
      brandBanner += " * Protected & Obfuscated — Do not modify.\n";
      brandBanner += " *========================================*/";

      for (const auto &p : config.obfuscateFolders) {
        fs::path target = encDir / p;
        if (!fs::exists(target))
          continue;

        auto processFile = [&](const fs::path &f) {
          FileUtil::StripLines(f, 2, 7);
          ifstream ifs(f);
          string content((istreambuf_iterator<char>(ifs)),
                         istreambuf_iterator<char>());
          ifs.close();
          auto pos = content.find('\n');
          if (pos != string::npos) {
            content.insert(pos + 1, brandBanner + "\n");
            ofstream ofs(f, ios::trunc);
            ofs << content;
          }
        };

        if (filesystem::is_directory(target)) {
          filesystem::path obfDir = target / "yakpro-po" / "obfuscated";
          if (filesystem::exists(obfDir)) {
            for (auto const &entry :
                 filesystem::recursive_directory_iterator(obfDir)) {
              if (entry.is_regular_file() && entry.path().extension() == ".php")
                processFile(entry.path());
            }
            // YakPro directory mode adds a redundant subfolder matching the
            // source name
            filesystem::path nestedObf =
                obfDir / filesystem::path(p).filename();
            if (filesystem::exists(nestedObf)) {
              filesystem::remove_all(rawDir / p);
              filesystem::copy(nestedObf, rawDir / p,
                               filesystem::copy_options::recursive);
            } else {
              filesystem::remove_all(rawDir / p);
              filesystem::copy(obfDir, rawDir / p,
                               filesystem::copy_options::recursive);
            }
          }
        } else {
          // its a single file
          processFile(target);
          filesystem::copy_file(target, rawDir / p,
                                filesystem::copy_options::overwrite_existing);
        }
      }

      // phase 2: layer-2 encoding (gzdeflate + base64)
      if (config.enableLayer2 && !config.layer2Files.empty()) {
        currentPhase = Phase::Layer2Encoding;
        log("=== Phase 2: Applying Layer-2 base64/gzdeflate encoding ===");

        filesystem::path encoderScript = tempBase / "layer2_encoder.php";
        {
          ofstream ofs(encoderScript);
          // this script preserves all header comments (brand banner,
          // user_comment, etc.) by scanning forward through whitespace,
          // single-line comments (//), and multi-line comments (/* */)
          // until real code is reached. only the code body gets encoded.
          ofs << "<?php\n"
              << "$f = $argv[1];\n"
              << "if (!file_exists($f)) { echo \"Error: File not found: "
                 "$f\\n\"; exit(1); }\n"
              << "$c = @file_get_contents($f);\n"
              << "if ($c === false) { echo \"Error: Cannot read file: $f\\n\"; "
                 "exit(1); }\n"
              << "\n"
              << "// Must start with <?php\n"
              << "if (!preg_match('/^<\\?php/', $c)) {\n"
              << "    echo \"Skipped (no PHP tag): $f\\n\";\n"
              << "    exit(0);\n"
              << "}\n"
              << "\n"
              << "// Find the end of <?php tag\n"
              << "$pos = 5; // strlen('<?php')\n"
              << "$len = strlen($c);\n"
              << "\n"
              << "// Scan forward: consume whitespace + ALL comments\n"
              << "while ($pos < $len) {\n"
              << "    // Skip whitespace\n"
              << "    if (ctype_space($c[$pos])) { $pos++; continue; }\n"
              << "    // Skip single-line comment: // ...\n"
              << "    if ($pos + 1 < $len && $c[$pos] === '/' && $c[$pos+1] "
                 "=== '/') {\n"
              << "        $eol = strpos($c, \"\\n\", $pos);\n"
              << "        $pos = ($eol === false) ? $len : $eol + 1;\n"
              << "        continue;\n"
              << "    }\n"
              << "    // Skip multi-line comment: /* ... */\n"
              << "    if ($pos + 1 < $len && $c[$pos] === '/' && $c[$pos+1] "
                 "=== '*') {\n"
              << "        $end = strpos($c, '*/', $pos + 2);\n"
              << "        $pos = ($end === false) ? $len : $end + 2;\n"
              << "        continue;\n"
              << "    }\n"
              << "    // Not whitespace or comment — this is the code body "
                 "start\n"
              << "    break;\n"
              << "}\n"
              << "\n"
              << "$header = substr($c, 0, $pos);\n"
              << "$body   = substr($c, $pos);\n"
              << "if (trim($body) === '') {\n"
              << "    echo \"Skipped (empty body): $f\\n\";\n"
              << "    exit(0);\n"
              << "}\n"
              << "$enc = base64_encode(gzdeflate(trim($body), 9));\n"
              << "file_put_contents($f, $header . "
                 "\"eval(gzinflate(base64_decode('\" . $enc . \"')));\\n\");\n";
        }

        for (const auto &relPath : config.layer2Files) {
          filesystem::path target = rawDir / relPath;
          if (!filesystem::exists(target))
            continue;

          auto runL2 = [&](const filesystem::path &f) {
            if (f.extension() != ".php")
              return;
            string cmd =
                "php \"" + encoderScript.string() + "\" \"" + f.string() + "\"";
            runCommandWithOutput(cmd);
          };

          if (filesystem::is_directory(target)) {
            for (auto const &entry :
                 filesystem::recursive_directory_iterator(target)) {
              if (entry.is_regular_file())
                runL2(entry.path());
            }
          } else {
            runL2(target);
          }
        }
      }

      //phase 3: seed injection
      if (config.enableDecoys && !config.seedFolderPath.empty()) {
        currentPhase = Phase::SeedInjection;
        log("=== Phase 3: Injecting decoy / seed files ===");
        if (!FileUtil::MergeDirectory(config.seedFolderPath, rawDir,
                                      logCallback)) {
          log("  [WARN] Seed injection failed or folder empty.");
        } else {
          log("  [OK] Seed files merged recursively.");
        }
      }

      // phase 4: packaging
      if (config.enablePackaging) {
        currentPhase = Phase::Packaging;
        log("=== Phase 4: Packaging ===");
        filesystem::path distDir =
            filesystem::path(config.projectPath) / "dist";
        filesystem::create_directories(distDir);

        string fullZip =
            (distDir / ("product_full_" + config.version + ".zip")).string();
        string updateZip =
            (distDir / ("product_update_" + config.version + ".zip")).string();

        //full package
        log("  [PKG] Assembling Full Release archive...");
        FileUtil::ZipDirectory(rawDir, fullZip);
        log("  [OK] Full package: " + fullZip);

        //update package
        filesystem::path updateTmp = tempBase / "update";
        filesystem::create_directories(updateTmp);
        for (const auto &f : config.updatePackageIncludes) {
          if (filesystem::exists(rawDir / f)) {
            if ((updateTmp / f).has_parent_path()) {
              filesystem::create_directories((updateTmp / f).parent_path());
            }
            filesystem::copy(rawDir / f, updateTmp / f,
                             filesystem::copy_options::recursive |
                                 filesystem::copy_options::overwrite_existing);
          }
        }
        FileUtil::ZipDirectory(updateTmp, updateZip);
        log("  [OK] Update package: " + updateZip);
      }

      currentPhase = Phase::Completed;
      log("=== [ BUILD SUCCESSFUL ] ===");
      log("Output: " +
          (filesystem::path(config.projectPath) / "dist").string());

    } catch (const exception &e) {
      currentPhase = Phase::Failed;
      log("=== BUILD FAILED: " + string(e.what()) + " ===");
    }
  }).detach();
}
